# Generated by Django 2.2.5 on 2019-10-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do Quarto'),
        ),
    ]
