# Generated by Django 2.2.5 on 2019-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0004_auto_20191015_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/images/', verbose_name='Imagem do quarto'),
        ),
    ]
