# Generated by Django 2.2.5 on 2019-10-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0005_auto_20191015_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='.images/', verbose_name='Imagem do quarto'),
        ),
    ]
