# Generated by Django 2.2.5 on 2019-10-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('description', models.TextField(max_length=100, verbose_name='Descrição')),
                ('active', models.BooleanField(default=False, verbose_name='Selecionar como primeiro slide')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do slide')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='Quemsomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Descrição')),
                ('mission', models.TextField(max_length=300, verbose_name='Missão')),
                ('vision', models.TextField(max_length=300, verbose_name='Visão')),
                ('value', models.TextField(max_length=300, verbose_name='Valores')),
            ],
            options={
                'verbose_name': 'Quem Somos',
                'verbose_name_plural': 'Quem Somos',
            },
        ),
    ]
