# Generated by Django 2.2.5 on 2019-10-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
