# Generated by Django 2.2.5 on 2019-10-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('description', models.TextField(max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Título'),
        ),
    ]
