# Generated by Django 2.2.5 on 2019-10-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_auto_20191015_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Selecionar como primeiro slide'),
        ),
    ]
