# Generated by Django 2.2.5 on 2019-10-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_remove_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do slide'),
        ),
    ]
