# Generated by Django 2.2.5 on 2019-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=300, verbose_name='Missão')),
                ('telephone', models.TextField(max_length=300, verbose_name='Visão')),
                ('email', models.TextField(max_length=300, verbose_name='Valores')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contato',
            },
        ),
    ]
