# Generated by Django 2.2.5 on 2019-10-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0005_auto_20191018_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='address',
            field=models.TextField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.TextField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telephone',
            field=models.TextField(max_length=100, verbose_name='Telefone'),
        ),
    ]
